# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: 
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
jobs:
  test_push:
    strategy:
       matrix:
        node-version: [18.x]
        test_cmd: 
          - yarn playwright install --with-deps && yarn test:node --roots ./docs ./packages/log ./packages/clients --w 2 && yarn test:browser
          - yarn test:node --roots ./packages/programs --w 2
          - yarn test:node --roots ./packages/transport ./packages/utils --w 2

    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: |
          yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Tests
        run: ${{matrix.test_cmd}}

  test_pr:
    if: github.event_name == 'pull_request'
    strategy:
        matrix:
            os: [ ubuntu-22.04 ]
            node-version: [18.x]
            test_cmd: 
              - yarn playwright install --with-deps && yarn test:node --roots ./packages/clients ./packages/log --w 2 && yarn test:browser
              - yarn test:node --roots ./packages/programs ./docs  --w 2
              - yarn test:node --roots ./packages/transport ./packages/utils --w 2

    name: Test (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: |
          yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Tests
        run: ${{matrix.test_cmd}}

